# systems/n64/n64_conversion_table.py

from .n64_constants import (
    EEP_EXT, SRA_EXT, FLA_EXT, MPK_EXT, SRM_EXT,
    SIZE_EEP, SIZE_SRA, SIZE_FLA, SIZE_MPK, SIZE_SRM,
    SIZE_SRA_SRM_OFFSET, SIZE_FLA_SRM_OFFSET, SIZE_MPK_SRM_OFFSET,
    EEP_LABEL, SRA_LABEL, FLA_LABEL, MPK_LABEL, SRM_LABEL,
    NATIVE_LABEL, PJ64_LABEL, RA_LABEL, WII_LABEL
)

# N64 Conversion table
conversion_table = {
    # WII → RA/PJ64/NATIVE
    f"{WII_LABEL}-{EEP_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_EEP, SIZE_SRM, 0, False, SRM_EXT),
    f"{WII_LABEL}-{EEP_LABEL}-{NATIVE_LABEL}-{EEP_LABEL}": (SIZE_EEP, SIZE_EEP, 0, False, EEP_EXT),
    f"{WII_LABEL}-{SRA_LABEL}-{PJ64_LABEL}-{SRA_LABEL}": (SIZE_SRA, SIZE_SRA, 0, True, SRA_EXT),
    f"{WII_LABEL}-{SRA_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_SRA, SIZE_SRM, SIZE_SRA_SRM_OFFSET, True, SRM_EXT),
    f"{WII_LABEL}-{SRA_LABEL}-{NATIVE_LABEL}-{SRA_LABEL}": (SIZE_SRA, SIZE_SRA, 0, False, SRA_EXT),
    f"{WII_LABEL}-{FLA_LABEL}-{PJ64_LABEL}-{FLA_LABEL}": (SIZE_FLA, SIZE_FLA, 0, True, FLA_EXT),
    f"{WII_LABEL}-{FLA_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_FLA, SIZE_SRM, SIZE_FLA_SRM_OFFSET, True, SRM_EXT),
    f"{WII_LABEL}-{FLA_LABEL}-{NATIVE_LABEL}-{FLA_LABEL}": (SIZE_FLA, SIZE_FLA, 0, False, FLA_EXT),
    f"{WII_LABEL}-{MPK_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_MPK, SIZE_SRM, SIZE_MPK_SRM_OFFSET, False, SRM_EXT),
    f"{WII_LABEL}-{MPK_LABEL}-{NATIVE_LABEL}-{MPK_LABEL}": (SIZE_MPK, SIZE_MPK, 0, False, MPK_EXT),
    # PJ64 → RA/WII/NATIVE
    f"{PJ64_LABEL}-{EEP_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_EEP, SIZE_SRM, 0, False, SRM_EXT),
    f"{PJ64_LABEL}-{EEP_LABEL}-{NATIVE_LABEL}-{EEP_LABEL}": (SIZE_EEP, SIZE_EEP, 0, False, EEP_EXT),
    f"{PJ64_LABEL}-{SRA_LABEL}-{WII_LABEL}-{SRA_LABEL}": (SIZE_SRA, SIZE_SRA, 0, True, SRA_EXT),
    f"{PJ64_LABEL}-{SRA_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_SRA, SIZE_SRM, SIZE_SRA_SRM_OFFSET, False, SRM_EXT),
    f"{PJ64_LABEL}-{SRA_LABEL}-{NATIVE_LABEL}-{SRA_LABEL}": (SIZE_SRA, SIZE_SRA, 0, False, SRA_EXT),
    f"{PJ64_LABEL}-{FLA_LABEL}-{WII_LABEL}-{FLA_LABEL}": (SIZE_FLA, SIZE_FLA, 0, True, FLA_EXT),
    f"{PJ64_LABEL}-{FLA_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_FLA, SIZE_SRM, SIZE_FLA_SRM_OFFSET, False, SRM_EXT),
    f"{PJ64_LABEL}-{FLA_LABEL}-{NATIVE_LABEL}-{FLA_LABEL}": (SIZE_FLA, SIZE_FLA, 0, False, FLA_EXT),
    f"{PJ64_LABEL}-{MPK_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_MPK, SIZE_SRM, SIZE_MPK_SRM_OFFSET, False, SRM_EXT),
    f"{PJ64_LABEL}-{MPK_LABEL}-{NATIVE_LABEL}-{MPK_LABEL}": (SIZE_MPK, SIZE_MPK, 0, False, MPK_EXT),
    # RA → PJ64/WII/NATIVE
    f"{RA_LABEL}-{SRM_LABEL}-{WII_LABEL}-{EEP_LABEL}": (SIZE_SRM, SIZE_EEP, 0, False, EEP_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{WII_LABEL}-{SRA_LABEL}": (SIZE_SRM, SIZE_SRA, -SIZE_SRA_SRM_OFFSET, True, SRA_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{WII_LABEL}-{FLA_LABEL}": (SIZE_SRM, SIZE_FLA, -SIZE_FLA_SRM_OFFSET, True, FLA_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{WII_LABEL}-{MPK_LABEL}": (SIZE_SRM, SIZE_MPK, -SIZE_MPK_SRM_OFFSET, False, MPK_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{WII_LABEL}-{NATIVE_LABEL}": (SIZE_SRM, SIZE_SRA, -SIZE_SRA_SRM_OFFSET, True, SRA_EXT),  # generic example
    f"{RA_LABEL}-{SRM_LABEL}-{PJ64_LABEL}-{EEP_LABEL}": (SIZE_SRM, SIZE_EEP, 0, False, EEP_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{PJ64_LABEL}-{SRA_LABEL}": (SIZE_SRM, SIZE_SRA, -SIZE_SRA_SRM_OFFSET, False, SRA_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{PJ64_LABEL}-{FLA_LABEL}": (SIZE_SRM, SIZE_FLA, -SIZE_FLA_SRM_OFFSET, False, FLA_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{PJ64_LABEL}-{MPK_LABEL}": (SIZE_SRM, SIZE_MPK, -SIZE_MPK_SRM_OFFSET, False, MPK_EXT),
    f"{RA_LABEL}-{SRM_LABEL}-{NATIVE_LABEL}-{SRA_LABEL}": (SIZE_SRM, SIZE_SRA, -SIZE_SRA_SRM_OFFSET, False, SRA_EXT),
    # NATIVE → Anything else (raw dump, no offset)
    f"{NATIVE_LABEL}-{EEP_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_EEP, SIZE_SRM, 0, False, SRM_EXT),
    f"{NATIVE_LABEL}-{SRA_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_SRA, SIZE_SRM, SIZE_SRA_SRM_OFFSET, True, SRM_EXT),
    f"{NATIVE_LABEL}-{FLA_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_FLA, SIZE_SRM, SIZE_FLA_SRM_OFFSET, True, SRM_EXT),
    f"{NATIVE_LABEL}-{MPK_LABEL}-{RA_LABEL}-{SRM_LABEL}": (SIZE_MPK, SIZE_SRM, SIZE_MPK_SRM_OFFSET, False, SRM_EXT),
    f"{NATIVE_LABEL}-{EEP_LABEL}-{PJ64_LABEL}-{EEP_LABEL}": (SIZE_EEP, SIZE_EEP, 0, False, EEP_EXT),
    f"{NATIVE_LABEL}-{SRA_LABEL}-{PJ64_LABEL}-{SRA_LABEL}": (SIZE_SRA, SIZE_SRA, 0, True, SRA_EXT),
    f"{NATIVE_LABEL}-{FLA_LABEL}-{PJ64_LABEL}-{FLA_LABEL}": (SIZE_FLA, SIZE_FLA, 0, True, FLA_EXT),
    f"{NATIVE_LABEL}-{MPK_LABEL}-{PJ64_LABEL}-{MPK_LABEL}": (SIZE_MPK, SIZE_MPK, 0, False, MPK_EXT),
}
